"""empty message

Revision ID: 156d82507034
Revises: 5b992fb256b5
Create Date: 2021-01-20 14:31:15.595356

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '156d82507034'
down_revision = '5b992fb256b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    # ### end Alembic commands ###
